#!/bin/bash

g="\033[1;32m"
y="\033[1;33m"
w="\033[0;37m"
if [ -e chrome-remote-desktop_current_amd64.deb ]
then
    sudo dpkg --install chrome-remote-desktop_current_amd64.deb
    sudo apt install --assume-yes --fix-broken
else
    wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb 
    sudo dpkg --install chrome-remote-desktop_current_amd64.deb
    sudo apt install --assume-yes --fix-broken
fi
DEBIAN_FRONTEND=noninteractive
sudo apt install mate-desktop-environment
sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/mate-session" > /etc/chrome-remote-desktop-session'
sudo apt install --assume-yes xscreensaver
sudo apt install --assume-yes --fix-broken
sudo apt install firefox-esr

sudo systemctl disable lightdm.service
sudo apt install nautilus nano -y
clear

echo -e "${w}  Visit: https://remotedesktop.google.com/headless"
